import jsPDF from 'jspdf';
import {
  M, CW, C, rgb, pdfToBase64,
  drawHeaderBand, drawControlStrip, sectionBand,
  drawInfoTable, drawVitalsGrid, drawMedicationTable,
  drawBillingSummaryRow, drawSignatureBlock,
  drawFooter,
  wrappedText, formatAddress,
} from './pdfCommon';

// ─── TYPES ─────────────────────────────────────────────────────────────────

export interface HospitalInfo {
  name: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  state?: string;
  country?: string;
  phone?: string;
  email?: string;
  website?: string;
  gstNumber?: string;
}

export interface VitalsInfo {
  recordedAt?: string;
  height?: number | string;
  weight?: number | string;
  bloodPressureSystolic?: number;
  bloodPressureDiastolic?: number;
  heartRate?: number;
  temperature?: number | string;
  bmi?: number | string;
  oxygenSaturation?: number;
  respiratoryRate?: number;
}

export interface PrescriptionItem {
  medicineName: string;
  dosage?: string;
  frequency?: string;
  duration?: string;
  instructions?: string;
}

export interface LabOrderItem {
  testName: string;
  testType?: string;
  priority?: string;
}

export interface ConsultationInfo {
  chiefComplaint?: string;
  provisionalDiagnosis?: string;
  finalDiagnosis?: string;
  notes?: string;
  followUpDate?: string;
  prescriptions?: PrescriptionItem[];
  labOrders?: LabOrderItem[];
}

export interface OPDCardData {
  opdCardNumber: string;
  issueDate: string;
  hospital: HospitalInfo;
  patient: {
    name: string;
    uhid: string;
    age: number | string;
    gender: string;
    mobile: string;
    address?: string | Record<string, any>;
    relationName?: string;
  };
  appointment: {
    doctor: string;
    doctorRegistrationNo?: string;
    doctorSignatureBase64?: string;
    department?: string;
    fees?: string;
    paymentMode?: string;
  };
  generatedBy?: string;
  vitals?: VitalsInfo;
  consultation?: ConsultationInfo;
}

// ─── Vitals builder (shared across generators) ─────────────────────────────

function buildVitalsItems(v: VitalsInfo): [string, string][] {
  const items: [string, string][] = [];
  if (v.height != null)                items.push(['Height',      `${v.height} ft`]);
  if (v.weight != null)                items.push(['Weight',      `${v.weight} kg`]);
  if (v.bloodPressureSystolic != null) items.push(['BP',          `${v.bloodPressureSystolic}/${v.bloodPressureDiastolic} mmHg`]);
  if (v.heartRate != null)             items.push(['Pulse',       `${v.heartRate} bpm`]);
  if (v.temperature != null)           items.push(['Temperature', `${v.temperature} °F`]);
  if (v.bmi != null)                   items.push(['BMI',         `${v.bmi}`]);
  if (v.oxygenSaturation != null)      items.push(['O₂ Sat',     `${v.oxygenSaturation}%`]);
  if (v.respiratoryRate != null)       items.push(['Resp Rate',   `${v.respiratoryRate}/min`]);
  return items;
}

// ─── MAIN GENERATOR ────────────────────────────────────────────────────────

export const generateOPDCardPDF = (data: OPDCardData): string => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y: number;

  // ── Header band ────────────────────────────────────────────────────────
  y = drawHeaderBand(doc, data.hospital, 'OPD Card',
    data.hospital.gstNumber ? `GST: ${data.hospital.gstNumber}` : undefined);

  // ── Control strip ──────────────────────────────────────────────────────
  y = drawControlStrip(doc, y, `Card No: ${data.opdCardNumber}`, `Date: ${data.issueDate}`);
  y += 4;

  // ── Patient Information ────────────────────────────────────────────────
  y = sectionBand(doc, y, 'Patient Information');
  y = drawInfoTable(doc, y, [
    ['UHID',         data.patient.uhid || '—',    'Date',       data.issueDate],
    ['Name',         data.patient.name || '—',    'Contact',    data.patient.mobile || '—'],
    ['Age / Gender', `${data.patient.age ?? '—'} / ${data.patient.gender || '—'}`, 'Address', formatAddress(data.patient.address)],
    ['Doctor',       data.appointment.doctor || '—',  'Department', data.appointment.department || '—'],
    ['Fees',         data.appointment.fees || '₹0',   'Mode',       data.appointment.paymentMode || '—'],
    ['Generated By', data.generatedBy || 'System',    'Relation',   data.patient.relationName || '—'],
  ]);

  // ── OPD Timing ─────────────────────────────────────────────────────────
  rgb(doc, C.stripBg, 'fill');
  doc.rect(M, y, CW, 7.5, 'F');
  rgb(doc, C.border, 'draw');
  doc.setLineWidth(0.25);
  doc.rect(M, y, CW, 7.5);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  rgb(doc, C.navy, 'text');
  doc.text('OPD TIMING:', M + 3, y + 5.2);
  doc.setFont('helvetica', 'normal');
  rgb(doc, C.txtSec, 'text');
  doc.text('MON – SAT  |  09:00 AM – 06:00 PM', M + 30, y + 5.2);
  y += 11;

  // ── Vitals ─────────────────────────────────────────────────────────────
  if (data.vitals) {
    const recLabel = data.vitals.recordedAt ? `Recorded: ${data.vitals.recordedAt}` : undefined;
    y = sectionBand(doc, y, 'Vitals', C.navy, recLabel);
    const vItems = buildVitalsItems(data.vitals);
    if (vItems.length > 0) y = drawVitalsGrid(doc, y, vItems);
  }

  // ── Chief Complaint ────────────────────────────────────────────────────
  const c = data.consultation;
  y = sectionBand(doc, y, 'Chief Complaint / Symptoms');

  const chiefComplaintText = c?.chiefComplaint?.trim() || '';
  if (chiefComplaintText) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    const lines = doc.splitTextToSize(chiefComplaintText, CW - 6);
    const boxH = Math.max(lines.length * 5 + 6, 22);
    rgb(doc, C.lightBg, 'fill');
    rgb(doc, C.border, 'draw');
    doc.setLineWidth(0.3);
    doc.rect(M, y, CW, boxH, 'FD');
    doc.text(lines, M + 3, y + 6);
    y += boxH + 5;
  } else {
    doc.setFillColor(252, 254, 255);
    rgb(doc, C.border, 'draw');
    doc.setLineWidth(0.3);
    doc.rect(M, y, CW, 28, 'FD');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(200, 210, 220);
    doc.text('(To be filled by the doctor / receptionist)', M + 3, y + 8);
    y += 33;
  }

  // ── Diagnosis ──────────────────────────────────────────────────────────
  if (c?.provisionalDiagnosis || c?.finalDiagnosis) {
    y = sectionBand(doc, y, 'Diagnosis', C.teal);
    if (c.provisionalDiagnosis) {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      rgb(doc, C.txtSec, 'text');
      doc.text('Provisional:', M + 2, y);
      doc.setFont('helvetica', 'normal');
      rgb(doc, C.black, 'text');
      doc.text(doc.splitTextToSize(c.provisionalDiagnosis, CW - 30)[0], M + 28, y);
      y += 6;
    }
    if (c.finalDiagnosis) {
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      rgb(doc, C.navy, 'text');
      doc.text('Final Diagnosis:', M + 2, y);
      doc.setFont('helvetica', 'normal');
      rgb(doc, C.black, 'text');
      doc.text(doc.splitTextToSize(c.finalDiagnosis, CW - 38)[0], M + 36, y);
      y += 6;
    }
    y += 2;
  }

  // ── Prescription ───────────────────────────────────────────────────────
  if (c?.prescriptions && c.prescriptions.length > 0) {
    y = sectionBand(doc, y, `Prescription  (${c.prescriptions.length} Medicine${c.prescriptions.length > 1 ? 's' : ''})`);
    const noop = () => {};
    y = drawMedicationTable(doc, y, c.prescriptions, noop);
  }

  // ── Investigations ─────────────────────────────────────────────────────
  if (c?.labOrders && c.labOrders.length > 0) {
    y = sectionBand(doc, y, `Investigations  (${c.labOrders.length})`);
    const perCol = Math.ceil(c.labOrders.length / 2);
    const half = perCol;
    const colXArr = [M + 2, M + CW / 2 + 2];
    for (let i = 0; i < perCol; i++) {
      const left = c.labOrders[i];
      const right = c.labOrders[i + half];
      if (left) {
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'normal');
        rgb(doc, C.black, 'text');
        doc.text(`${i + 1}. ${left.testName}`, colXArr[0], y);
      }
      if (right) {
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'normal');
        rgb(doc, C.black, 'text');
        doc.text(`${i + half + 1}. ${right.testName}`, colXArr[1], y);
      }
      y += 5;
    }
    y += 3;
  }

  // ── Follow-up ──────────────────────────────────────────────────────────
  if (c?.followUpDate) {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    rgb(doc, C.navy, 'text');
    doc.text('Follow-up Date:', M + 2, y);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    doc.text(
      new Date(c.followUpDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
      M + 34, y,
    );
    y += 7;
  }

  // ── Notes ──────────────────────────────────────────────────────────────
  if (c?.notes) {
    y = sectionBand(doc, y, 'Notes / Instructions');
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    const used = wrappedText(doc, c.notes, M + 2, y, CW - 4);
    y += Math.max(used, 4) + 5;
  }

  // ── Signature block ────────────────────────────────────────────────────
  drawSignatureBlock(doc, 241, data.appointment.doctor, undefined,
    data.appointment.doctorRegistrationNo, data.appointment.doctorSignatureBase64);

  // ── Footer ─────────────────────────────────────────────────────────────
  drawFooter(doc, data.generatedBy, `OPD Card: ${data.opdCardNumber}`);

  const base64 = pdfToBase64(doc);
  doc.save(`OPD-Card-${data.opdCardNumber}.pdf`);
  return base64;
};

// ─── PRESCRIPTION PDF TYPES ───────────────────────────────────────────────

export interface PrescriptionPDFData {
  hospital: HospitalInfo;
  patient: { name: string; uhid: string; age: string | number; gender: string; mobile: string };
  doctor: { name: string; specialization?: string; registrationNo?: string; department?: string; signatureBase64?: string };
  diagnosis?: string;
  prescriptions: PrescriptionItem[];
  notes?: string;
  followUpDate?: string;
  date: string;
}

// ─── PRESCRIPTION PDF GENERATOR ───────────────────────────────────────────

export const generatePrescriptionPDF = (data: PrescriptionPDFData): string => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y: number;

  const checkPage = (needed = 14) => { if (y + needed > 270) { doc.addPage(); y = 15; } };

  // ── Header band ────────────────────────────────────────────────────────
  y = drawHeaderBand(doc, data.hospital, 'Prescription');

  // ── Control strip ──────────────────────────────────────────────────────
  y = drawControlStrip(doc, y, `UHID: ${data.patient.uhid}`, `Date: ${data.date}`);
  y += 4;

  // ── Patient Information ────────────────────────────────────────────────
  y = sectionBand(doc, y, 'Patient Information');
  y = drawInfoTable(doc, y, [
    ['Name',         data.patient.name || '—', 'UHID',    data.patient.uhid || '—'],
    ['Age / Gender', `${data.patient.age ?? '—'} / ${data.patient.gender || '—'}`, 'Contact', data.patient.mobile || '—'],
  ]);

  // ── Doctor Information ─────────────────────────────────────────────────
  y = sectionBand(doc, y, 'Doctor Information');
  y = drawInfoTable(doc, y, [
    ['Doctor',         data.doctor.name || '—',           'Department',    data.doctor.department || '—'],
    ['Specialization', data.doctor.specialization || '—',  'Reg. No',      data.doctor.registrationNo || '—'],
  ]);

  // ── Diagnosis ──────────────────────────────────────────────────────────
  if (data.diagnosis) {
    checkPage(20);
    y = sectionBand(doc, y, 'Diagnosis', C.teal);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    const dLines = doc.splitTextToSize(data.diagnosis, CW - 6);
    const dBoxH = Math.max(dLines.length * 5 + 6, 14);
    rgb(doc, C.lightBg, 'fill');
    rgb(doc, C.border, 'draw');
    doc.setLineWidth(0.3);
    doc.rect(M, y, CW, dBoxH, 'FD');
    doc.text(dLines, M + 3, y + 6);
    y += dBoxH + 4;
  }

  // ── Prescription Table ─────────────────────────────────────────────────
  checkPage(20);
  y = sectionBand(doc, y, `Prescription  (${data.prescriptions.length} Medicine${data.prescriptions.length > 1 ? 's' : ''})`);
  y = drawMedicationTable(doc, y, data.prescriptions, checkPage);

  // ── Notes ──────────────────────────────────────────────────────────────
  if (data.notes) {
    checkPage(18);
    y = sectionBand(doc, y, 'Notes / Instructions');
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    const used = wrappedText(doc, data.notes, M + 2, y, CW - 4);
    y += Math.max(used, 4) + 5;
  }

  // ── Follow-up ──────────────────────────────────────────────────────────
  if (data.followUpDate) {
    checkPage(10);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    rgb(doc, C.navy, 'text');
    doc.text('Follow-up Date:', M + 2, y);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    doc.text(
      new Date(data.followUpDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
      M + 34, y,
    );
    y += 7;
  }

  // ── Signature block ────────────────────────────────────────────────────
  drawSignatureBlock(doc, 241, data.doctor.name, data.doctor.specialization,
    data.doctor.registrationNo, data.doctor.signatureBase64);

  // ── Footer ─────────────────────────────────────────────────────────────
  drawFooter(doc);

  const base64 = pdfToBase64(doc);
  doc.save(`Prescription-${data.patient.uhid}-${data.date}.pdf`);
  return base64;
};

// ─── RECEIPT PDF TYPES ────────────────────────────────────────────────────

export interface ReceiptPDFData {
  hospital: HospitalInfo;
  patient: { name: string; uhid: string };
  receiptNumber: string;
  date: string;
  items: Array<{ description: string; amount: number }>;
  totalAmount: number;
  amountPaid: number;
  balance: number;
  paymentMethod: string;
  transactionRef?: string;
  generatedBy?: string;
}

// ─── RECEIPT PDF GENERATOR ────────────────────────────────────────────────

export const generateReceiptPDF = (data: ReceiptPDFData): string => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y: number;

  const checkPage = (needed = 14) => { if (y + needed > 270) { doc.addPage(); y = 15; } };
  const ROW_H = 7;
  const descW = CW - 40;

  // ── Header band ────────────────────────────────────────────────────────
  y = drawHeaderBand(doc, data.hospital, 'Payment Receipt',
    data.hospital.gstNumber ? `GST: ${data.hospital.gstNumber}` : undefined);

  // ── Control strip ──────────────────────────────────────────────────────
  y = drawControlStrip(doc, y, `Receipt No: ${data.receiptNumber}`, `Date: ${data.date}`);
  y += 4;

  // ── Patient Information ────────────────────────────────────────────────
  y = sectionBand(doc, y, 'Patient Information');
  y = drawInfoTable(doc, y, [
    ['Name', data.patient.name || '—', 'UHID', data.patient.uhid || '—'],
  ]);

  // ── Itemized Charges ───────────────────────────────────────────────────
  checkPage(20);
  y = sectionBand(doc, y, 'Itemized Charges');

  // Header row
  doc.setFillColor(230, 238, 252);
  doc.rect(M, y, CW, ROW_H, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  rgb(doc, C.navy, 'text');
  doc.text('Description', M + 2, y + ROW_H - 2.5);
  doc.text('Amount (₹)', M + CW - 2, y + ROW_H - 2.5, { align: 'right' });
  rgb(doc, C.border, 'draw');
  doc.setLineWidth(0.2);
  doc.line(M, y + ROW_H, M + CW, y + ROW_H);
  y += ROW_H;

  const tblStart = y - ROW_H;
  data.items.forEach((item, idx) => {
    checkPage(ROW_H);
    const ry = y;
    if (idx % 2 === 0) {
      rgb(doc, C.lightBg, 'fill');
      doc.rect(M, ry, CW, ROW_H, 'F');
    }
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    doc.text(doc.splitTextToSize(item.description, descW - 4)[0], M + 2, ry + ROW_H - 2.5);
    doc.setFont('helvetica', 'bold');
    doc.text(`₹${item.amount.toLocaleString('en-IN')}`, M + CW - 2, ry + ROW_H - 2.5, { align: 'right' });
    rgb(doc, C.border, 'draw');
    doc.setLineWidth(0.15);
    doc.line(M, ry + ROW_H, M + CW, ry + ROW_H);
    y += ROW_H;
  });

  rgb(doc, C.border, 'draw');
  doc.setLineWidth(0.4);
  doc.rect(M, tblStart, CW, (data.items.length + 1) * ROW_H);
  y += 4;

  // ── Summary Rows ───────────────────────────────────────────────────────
  checkPage(35);
  y = drawBillingSummaryRow(doc, y, 'Total Amount', `₹${data.totalAmount.toLocaleString('en-IN')}`, true);
  y = drawBillingSummaryRow(doc, y, 'Amount Paid', `₹${data.amountPaid.toLocaleString('en-IN')}`, false);
  y = drawBillingSummaryRow(doc, y, 'Balance', `₹${data.balance.toLocaleString('en-IN')}`, true);
  y += 2;

  // ── Payment Details ────────────────────────────────────────────────────
  checkPage(14);
  rgb(doc, C.stripBg, 'fill');
  doc.rect(M, y, CW, 7.5, 'F');
  rgb(doc, C.border, 'draw');
  doc.setLineWidth(0.25);
  doc.rect(M, y, CW, 7.5);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  rgb(doc, C.navy, 'text');
  doc.text('Payment Method:', M + 3, y + 5.2);
  doc.setFont('helvetica', 'normal');
  rgb(doc, C.txtSec, 'text');
  doc.text(data.paymentMethod, M + 36, y + 5.2);
  if (data.transactionRef) {
    doc.setFont('helvetica', 'bold');
    rgb(doc, C.navy, 'text');
    doc.text('Txn Ref:', M + CW / 2 + 3, y + 5.2);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.txtSec, 'text');
    doc.text(data.transactionRef, M + CW / 2 + 22, y + 5.2);
  }
  y += 11;

  // ── Footer ─────────────────────────────────────────────────────────────
  drawFooter(doc, data.generatedBy, `Receipt: ${data.receiptNumber}`);

  const base64 = pdfToBase64(doc);
  doc.save(`Receipt-${data.receiptNumber}.pdf`);
  return base64;
};

// ─── VISIT SUMMARY PDF TYPES ─────────────────────────────────────────────

export interface VisitSummaryData {
  hospital: HospitalInfo;
  patient: { name: string; uhid: string; age: string | number; gender: string; mobile: string };
  doctor: { name: string; specialization?: string; registrationNo?: string; signatureBase64?: string };
  visit: {
    date: string;
    department?: string;
    chiefComplaint?: string;
    diagnosis?: string;
    notes?: string;
    followUpDate?: string;
  };
  vitals?: VitalsInfo;
  prescriptions?: PrescriptionItem[];
  investigations?: Array<{ testName: string; status: string }>;
  billing?: { total: number; paid: number; balance: number; method?: string };
}

// ─── VISIT SUMMARY PDF GENERATOR ─────────────────────────────────────────

export const generateVisitSummaryPDF = (data: VisitSummaryData): string => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y: number;

  const checkPage = (needed = 14) => { if (y + needed > 270) { doc.addPage(); y = 15; } };

  // ── Header band ────────────────────────────────────────────────────────
  y = drawHeaderBand(doc, data.hospital, 'Visit Summary');

  // ── Control strip ──────────────────────────────────────────────────────
  y = drawControlStrip(doc, y, `UHID: ${data.patient.uhid}`, `Date: ${data.visit.date}`);
  y += 4;

  // ── Patient & Visit Info ───────────────────────────────────────────────
  y = sectionBand(doc, y, 'Patient & Visit Details');
  y = drawInfoTable(doc, y, [
    ['Name',           data.patient.name || '—',          'UHID',       data.patient.uhid || '—'],
    ['Age / Gender',   `${data.patient.age ?? '—'} / ${data.patient.gender || '—'}`, 'Contact', data.patient.mobile || '—'],
    ['Doctor',         data.doctor.name || '—',           'Department', data.visit.department || '—'],
    ['Specialization', data.doctor.specialization || '—',  'Reg. No',   data.doctor.registrationNo || '—'],
  ]);

  // ── Clinical Details ───────────────────────────────────────────────────
  if (data.visit.chiefComplaint || data.visit.diagnosis) {
    checkPage(25);
    y = sectionBand(doc, y, 'Clinical Details', C.teal);

    if (data.visit.chiefComplaint) {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      rgb(doc, C.txtSec, 'text');
      doc.text('Chief Complaint:', M + 2, y);
      doc.setFont('helvetica', 'normal');
      rgb(doc, C.black, 'text');
      const ccUsed = wrappedText(doc, data.visit.chiefComplaint, M + 34, y, CW - 36);
      y += Math.max(ccUsed, 5) + 2;
    }
    if (data.visit.diagnosis) {
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      rgb(doc, C.navy, 'text');
      doc.text('Diagnosis:', M + 2, y);
      doc.setFont('helvetica', 'normal');
      rgb(doc, C.black, 'text');
      const dxUsed = wrappedText(doc, data.visit.diagnosis, M + 28, y, CW - 30);
      y += Math.max(dxUsed, 5) + 2;
    }
    y += 2;
  }

  // ── Vitals ─────────────────────────────────────────────────────────────
  if (data.vitals) {
    checkPage(20);
    const recLabel = data.vitals.recordedAt ? `Recorded: ${data.vitals.recordedAt}` : undefined;
    y = sectionBand(doc, y, 'Vitals', C.navy, recLabel);
    const vItems = buildVitalsItems(data.vitals);
    if (vItems.length > 0) y = drawVitalsGrid(doc, y, vItems);
  }

  // ── Prescriptions ──────────────────────────────────────────────────────
  if (data.prescriptions && data.prescriptions.length > 0) {
    checkPage(20);
    y = sectionBand(doc, y, `Prescription  (${data.prescriptions.length} Medicine${data.prescriptions.length > 1 ? 's' : ''})`);
    y = drawMedicationTable(doc, y, data.prescriptions, checkPage);
  }

  // ── Investigations Ordered ─────────────────────────────────────────────
  if (data.investigations && data.investigations.length > 0) {
    checkPage(12);
    y = sectionBand(doc, y, `Investigations Ordered  (${data.investigations.length})`);

    const perCol = Math.ceil(data.investigations.length / 2);
    const half = perCol;
    const icx = [M + 2, M + CW / 2 + 2];

    for (let i = 0; i < perCol; i++) {
      checkPage(6);
      const left = data.investigations[i];
      const right = data.investigations[i + half];
      if (left) {
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'normal');
        rgb(doc, C.black, 'text');
        doc.text(`${i + 1}. ${left.testName}`, icx[0], y);
        doc.setFontSize(7);
        rgb(doc, C.txtSec, 'text');
        doc.text(`(${left.status})`, icx[0] + doc.getTextWidth(`${i + 1}. ${left.testName}`) + 2, y);
      }
      if (right) {
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'normal');
        rgb(doc, C.black, 'text');
        doc.text(`${i + half + 1}. ${right.testName}`, icx[1], y);
        doc.setFontSize(7);
        rgb(doc, C.txtSec, 'text');
        doc.text(`(${right.status})`, icx[1] + doc.getTextWidth(`${i + half + 1}. ${right.testName}`) + 2, y);
      }
      y += 5;
    }
    y += 3;
  }

  // ── Notes ──────────────────────────────────────────────────────────────
  if (data.visit.notes) {
    checkPage(18);
    y = sectionBand(doc, y, 'Notes / Instructions');
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    const used = wrappedText(doc, data.visit.notes, M + 2, y, CW - 4);
    y += Math.max(used, 4) + 5;
  }

  // ── Follow-up ──────────────────────────────────────────────────────────
  if (data.visit.followUpDate) {
    checkPage(10);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    rgb(doc, C.navy, 'text');
    doc.text('Follow-up Date:', M + 2, y);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.black, 'text');
    doc.text(
      new Date(data.visit.followUpDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
      M + 34, y,
    );
    y += 7;
  }

  // ── Payment Summary ────────────────────────────────────────────────────
  if (data.billing) {
    checkPage(35);
    y = sectionBand(doc, y, 'Payment Summary');
    y = drawBillingSummaryRow(doc, y, 'Total Billed', `₹${data.billing.total.toLocaleString('en-IN')}`, true);
    y = drawBillingSummaryRow(doc, y, 'Amount Paid', `₹${data.billing.paid.toLocaleString('en-IN')}`, false);
    y = drawBillingSummaryRow(doc, y, 'Balance', `₹${data.billing.balance.toLocaleString('en-IN')}`, true);
    if (data.billing.method) {
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      rgb(doc, C.txtSec, 'text');
      doc.text(`Payment Method: ${data.billing.method}`, M + 2, y + 2);
      y += 6;
    }
    y += 2;
  }

  // ── Signature block ────────────────────────────────────────────────────
  drawSignatureBlock(doc, 241, data.doctor.name, data.doctor.specialization,
    data.doctor.registrationNo, data.doctor.signatureBase64);

  // ── Footer ─────────────────────────────────────────────────────────────
  drawFooter(doc, undefined, `Visit: ${data.visit.date}`);

  const base64 = pdfToBase64(doc);
  doc.save(`VisitSummary-${data.patient.uhid}-${data.visit.date}.pdf`);
  return base64;
};
